apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-secret-store
spec:
  provider:
    onepasswordSDK:
      vault: homelab-credentials
      auth:
        serviceAccountSecretRef:
          namespace: apps-system
          name: one-password-home-lab-vault
          key: token

