apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-user-console
  namespace: minio-apps
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
  secretStoreRef:
    name: admin-user-console
    kind: ClusterSecretStore
  data:
    - secretKey: CONSOLE_ACCESS_KEY
      remoteRef:
        key: "MinioObject/adminConsoleAccess"
    - secretKey: CONSOLE_SECRET_KEY
      remoteRef:
        key: "MinioObject/adminConsoleSecretKey"

