apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: minio-apps
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "privateinternetaccess/password"

