apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: minio-apps
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
    deletionPolicy: Merge
  dataFrom:
    - extract:
        key: "privateinternetaccess"

