apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-user-login
  namespace: minio-apps
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        config.env: -|
          "{{ .ROOT_USER }}"
          "{{ .ROOT_PASSWORD }}"
          export MINIO_ROOT_USER="{{ .ROOT_USER }}"
          export MINIO_ROOT_PASSWORD="{{ .ROOT_PASSWORD }}"
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: ROOT_USER
      remoteRef:
        key: "MinioObject/rootUser"
    - secretKey: ROOT_PASSWORD
      remoteRef:
        key: "MinioObject/rootPassword"
