apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-user-login
  namespace: minio-apps
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        config.env: -|
          export MINIO_ROOT_USER='{{ "{{" }}.rootUser{{ "}}" }}'
          export MINIO_ROOT_PASSWORD='{{ "{{" }}.rootPassword{{ "}}" }}' # Unfortunately ArgoCD required that template is escaped, Ref: https://github.com/external-secrets/external-secrets/issues/972#issuecomment-2034681905
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: rootUser
      remoteRef:
        key: "MinioObject/rootUser"
    - secretKey: rootPassword
      remoteRef:
        key: "MinioObject/rootPassword"
