apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reactive-resume-db
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        username: '{{ "{{" }}.username{{ "}}" }}'
        password: '{{ "{{" }}.password{{ "}}" }}'
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "ReactiveResume/databaseUsername"
    - secretKey: password
      remoteRef:
        key: "ReactiveResume/databasePassword"
