apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reactive-resume
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        uri: postgresql://{{ "{{" }}.username{{ "}}" }}:{{ "{{" }}.password{{ "}}" }}@reactive-resume-db-rw:5432/reactive_resume
        username: '{{ "{{" }}.username{{ "}}" }}'
        password: '{{ "{{" }}.password{{ "}}" }}'
        authSecret: '{{ "{{" }}.authSecret{{ "}}" }}'
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "ReactiveResume/databaseUsername"
    - secretKey: password
      remoteRef:
        key: "ReactiveResume/databasePassword"
    - secretKey: authSecret
      remoteRef:
        key: "ReactiveResume/authSecret"
