apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reactive-resume-app
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        uri: postgresql://{{ "{{" }}.databaseUsername{{ "}}" }}:{{ "{{" }}.databasePassword{{ "}}" }}@reactive-resume-db-rw.resume-apps.svc.cluster.local:5432/reactive_resume
        authSecret: '{{ "{{" }}.authSecret{{ "}}" }}'
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: databaseUsername
      remoteRef:
        key: "ReactiveResume/databaseUsername"
    - secretKey: databasePassword
      remoteRef:
        key: "ReactiveResume/databasePassword"
    - secretKey: authSecret
      remoteRef:
        key: "ReactiveResume/authSecret"
