## Create a persistence claim for the storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reactive-resume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-storage-class

