longhorn:
  preUpgradeChecker:
    jobEnabled: false #https://github.com/longhorn/longhorn/issues/4853#issuecomment-2146991156
  longhornUI:
    replicas: 1
  persistence:
    defaultClass: false
    reclaimPolicy: Retain
    defaultDiskSelector:
      enable: true
      selector: "longhorn.io/san-disk-1tb"  # The disk in the node has already been labeled and annotated with this tag
  defaultSettings:
    defaultDataPath: "/mnt/local-volume/longhorn-data"
    createDefaultDiskLabeledNodes: "true"
    defaultReplicaCount: 2
    removeSnapshotsDuringFilesystemTrim: enabled
    storageMinimalAvailablePercentage: 30
    autoCleanupRecurringJobBackupSnapshot: "true"
    autoCleanupSystemGeneratedSnapshot: "true"
    concurrentAutomaticEngineUpgradePerNodeLimit: 3
    orphanAutoDeletion: "true"
    allowEmptyDiskSelectorVolume: "false"
    allowEmptyNodeSelectorVolume: "false"


#Node Label
#kubectl label node dlabs-control-plane node.longhorn.io/create-default-disk=config

#Node Annotation
#  k annotate nodes dlabs-control-plane   node.longhorn.io/default-disks-config='[{"name":"san-disk-ssd","path":"/mnt/local-volume/longhorn-data","allowScheduling":true,"tags":["san-disk-1tb"]},{"name":"on-node-storage","path":"/mnt/lv-90/longhorn-data","allowScheduling":true,"tags":["on-node-storage","fast"]}]' --overwrite
