media-server:
  controllers:
    vpn-tunnel:
      nameOverride: vpn-tunnel
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0 #Gluetun Needs to Modify the Network Stack
          fsGroup: 0
          fsGroupChangePolicy: OnRootMismatch

      containers:
        nzbget:
          image:
            repository: nzbgetcom/nzbget
            tag: latest
            pullPolicy: IfNotPresent
          env:
            PUID: 0
            PGID: 0
            TZ: "Europe/Berlin"
          envFrom:
            - secretRef:
                 name: media-server
          ports:
            - name: nzbget
              containerPort: 6789

        gluetun:
          dependsOn: nzbget
          image:
            repository: qmcgaw/gluetun
            tag: v3.40.0
            pullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            DNS_ADDRESS: "10.0.0.241" #Instead of using the K8s DNS, the VPN DNS is used, reference https://helpdesk.privateinternetaccess.com/kb/articles/using-pia-dns-in-custom-configurations
#            FIREWALL_VPN_INPUT_PORTS: 6789 For safetry this is not required, as the VPN is not exposed to the outside world
            FIREWALL_INPUT_PORTS: 6789 #This is the port that is use to expose the NZBGet service to other pods
            VPN_SERVICE_PROVIDER: "private internet access"
            SERVER_REGIONS: 'DE Berlin'
            TZ: "Europe/Berlin"
            SERVER_HOSTNAMES: "de-berlin.privacy.network"
          envFrom:
            - secretRef:
                name: media-server
    radarr:
      nameOverride: radarr
      strategy: Recreate
      pod:
          automountServiceAccountToken: true
          securityContext:
            runAsUser: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch

      containers:
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.22.4
            pullPolicy: IfNotPresent
          env:
            PUID: 0
            PGID: 0
            TZ: "Europe/Berlin"
          envFrom:
            - secretRef:
                name: media-server
          ports:
            - name: radarr
              containerPort: 7878
    jellyfin:
      nameOverride: jellyfin
      strategy: Recreate
      pod:
          automountServiceAccountToken: true
          securityContext:
            runAsUser: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch

      containers:
        jellyfin:
          image:
            repository: jellyfin/jellyfin
            tag: "2025050505"
            pullPolicy: IfNotPresent
          env:
            PUID: 0
            PGID: 0
            TZ: "Europe/Berlin"
          envFrom:
            - secretRef:
                name: media-server
          ports:
            - name: jellyfin
              containerPort: 8096
    jellyseer:
        nameOverride: jellyseer
        strategy: Recreate
        pod:
            automountServiceAccountToken: true
            securityContext:
                runAsUser: 0
                fsGroup: 0
                fsGroupChangePolicy: OnRootMismatch
        containers:
            jellyseer:
              image:
                  repository: ghcr.io/fallenbagel/jellyseerr
                  tag: latest
                  pullPolicy: IfNotPresent
              env:
                  TZ: "Europe/Berlin"
                  LOG_LEVEL: debug
              ports:
                - name: jellyseer
                  containerPort: 5055
    prowlarr:
      nameOverride: prowlarr
      strategy: Recreate
      pod:
          automountServiceAccountToken: true
          securityContext:
            runAsUser: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch

      containers:
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.35.1
            pullPolicy: IfNotPresent
          env:
            PUID: 1000
            PGID: 1000
            TZ: "Europe/Berlin"
          envFrom:
            - secretRef:
                name: media-server
          ports:
            - name: prowlarr
              containerPort: 9696

  service:
    vpn-tunnel:
      enabled: true
      nameOverride: vpn-tunnel
      controller: vpn-tunnel
      ports:
        nzbget:
          port: 6789
    radarr:
      enabled: true
      nameOverride: radarr
      controller: radarr
      ports:
        radarr:
          port: 7878
    jellyfin:
        enabled: true
        nameOverride: jellyfin
        controller: jellyfin
        ports:
            http:
              port: 8096
    prowlarr:
      enabled: true
      nameOverride: prowlarr
      controller: prowlarr
      ports:
        prowlarr:
          port: 9696
    jellyseer:
        enabled: true
        nameOverride: jellyseer
        controller: jellyseer
        ports:
          jellyseer:
              port: 5055

  ingress:
    jellyfin:
      enabled: true
      nameOverride: jellyfin
      hosts:
        - host: watch.oluwatobia.de
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: jellyfin
                port: http
    jellyseer:
      enabled: true
      nameOverride: jellyseer
      hosts:
        - host: media.oluwatobia.de
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: jellyseer
                port: jellyseer

  persistence:
    gluetun-tunnel-device:
      enabled: true
      type: hostPath
      hostPath: /dev/net/tun
      hostPathType: "CharDevice"
      advancedMounts:
        vpn-tunnel:
          gluetun:
            - path: /dev/net/tun
    gpu-accelerator:
      enabled: true
      type: hostPath
      hostPath: /dev/dri/renderD128
      advancedMounts:
        jellyfin:
          jellyfin:
            - path: /dev/dri/renderD128
    gluetun-volume:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Gi
      nameOverride: media-server-pvc
      storageClass: media-server-storage-class
      advancedMounts:
        vpn-tunnel:
          gluetun:
            - path: /gluetun
              subPath: config/gluetun
              readOnly: false
          nzbget:
            - path: /config
              subPath: config/nzbget
              readOnly: false
            - path: /data/usenet
              subPath: usenet
              readOnly: false
        radarr:
          radarr:
            - path: /config
              subPath: config/radarr
              readOnly: false
            - path: /data
              readOnly: false
        jellyfin:
          jellyfin:
            - path: /config
              subPath: config/jellyfin
              readOnly: false
            - path: /cache
              subPath: config/jellyfin/cache
            - path: /media
              subPath: media
              readOnly: false
        jellyseer:
          jellyseer:
            - path: /app/config
              subPath: config/jellyseer
              readOnly: false
        prowlarr:
          prowlarr:
            - path: /config
              subPath: config/prowlarr
              readOnly: false















