media-server:
  controllers:
    gluetun:
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
        restartPolicy: Always
      containers:
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest
            pullPolicy: IfNotPresent
          capabilities:
            add:
              - NET_ADMIN
          env:
            VPN_SERVICE_PROVIDER: custom
            VPN_TYPE: wireguard
            TZ: "Europe/Berlin"
            VPN_INTERFACE: wg0
  persistence:
    gluetun-tunnel-device:
      enabled: true
      type: hostPath
      hostPath: /dev/net/tun
      hostPathType: "CharDevice"
      advancedMounts:
        gluetun:
          gluetun:
            - path: /dev/net/tun
    glutun-wireguard-config:
      enabled: true
      type: secret
      name: gluetun-wireguard-config
      advancedMounts:
        gluetun:
          gluetun:
           -  path: /glutun/wireguard/wg0.conf
              readOnly: true
    gluetun-volume:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Gi
      storageClass: media-server-storage-class
      advancedMounts:
        gluetun:
          gluetun:
            - path: /glutun
              readOnly: false











