media-server:
  controllers:
    vpn-tunnel:
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0 #Gluetun Needs to Modify the Network Stack
          fsGroup: 0
          fsGroupChangePolicy: OnRootMismatch

      containers:
        nzbget:
          image:
            repository: nzbgetcom/nzbget
            tag: latest
            pullPolicy: IfNotPresent
          env:
            PUID: 1000
            PGID: 1000
            TZ: "Europe/Berlin"
          envFrom:
            - secretRef:
                 name: media-server
          ports:
            - name: nzbget
              containerPort: 6789

        gluetun:
          dependsOn: nzbget
          image:
            repository: qmcgaw/gluetun
            tag: v3.40.0
            pullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            DOT: off
            FIREWALL_VPN_INPUT_PORTS: 6789
            VPN_SERVICE_PROVIDER: "private internet access"
            SERVER_REGIONS: 'DE Berlin'
            TZ: "Europe/Berlin"
            SERVER_HOSTNAMES: "de-berlin.privacy.network"
          envFrom:
            - secretRef:
                name: media-server
  service:
    vpn-tunnel:
      controller: vpn-tunnel
      ports:
        nzbget:
          port: 6789
  persistence:
    gluetun-tunnel-device:
      enabled: true
      type: hostPath
      hostPath: /dev/net/tun
      hostPathType: "CharDevice"
      advancedMounts:
        vpn-tunnel:
          gluetun:
            - path: /dev/net/tun
    gluetun-volume:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Gi
      nameOverride: media-server-pvc
      storageClass: media-server-storage-class
      advancedMounts:
        vpn-tunnel:
          gluetun:
            - path: /gluetun
              subPath: config/gluetun
              readOnly: false
          nzbget:
            - path: /config
              subPath: config/nzbget
              readOnly: false
            - path: /downloads
              subPath: downloads
              readOnly: false











