media-server:
  controllers:
    gluetun:
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
          fsGroup: 1000 #
          fsGroupChangePolicy: OnRootMismatch

      containers:
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest
            pullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            VPN_SERVICE_PROVIDER: "private internet access"
            SERVER_REGIONS: 'Netherlands'
            TZ: "Europe/Berlin"
            SERVER_NAMES: "amsterdam441"
            SERVER_HOSTNAMES: "nl-amsterdam.privacy.network"
          envFrom:
            - secretRef:
                name: gluetun-wireguard-config

  persistence:
    gluetun-tunnel-device:
      enabled: true
      type: hostPath
      hostPath: /dev/net/tun
      hostPathType: "CharDevice"
      advancedMounts:
        gluetun:
          gluetun:
            - path: /dev/net/tun
    gluetun-volume:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Gi
      nameOverride: media-server-pvc
      storageClass: media-server-storage-class
      advancedMounts:
        gluetun:
          gluetun:
            - path: /glutun
              readOnly: false











