media-server:
  controllers:
    gluetun:
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0 #Gluetun Needs to Modify the Network Stack
          fsGroup: 0
          fsGroupChangePolicy: OnRootMismatch

      containers:
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest
            pullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            VPN_SERVICE_PROVIDER: "private internet access"
            SERVER_REGIONS: 'NL Netherlands Streaming Optimized'
            TZ: "Europe/Berlin"
            SERVER_NAMES: "amsterdam404"
            SERVER_HOSTNAMES: "nl-netherlands-so.privacy.network"
          envFrom:
            - secretRef:
                name: gluetun-wireguard-config
          probes:
            liveness:
              enabled: true
              spec:
                httpGet:
                  path: /
                  port: 9999
                initialDelaySeconds: 10
                periodSeconds: 10
            readiness:
              httpGet:
                path: /
                port: 9999
              initialDelaySeconds: 10
              periodSeconds: 10


  persistence:
    gluetun-tunnel-device:
      enabled: true
      type: hostPath
      hostPath: /dev/net/tun
      hostPathType: "CharDevice"
      advancedMounts:
        gluetun:
          gluetun:
            - path: /dev/net/tun
    gluetun-volume:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Gi
      nameOverride: media-server-pvc
      storageClass: media-server-storage-class
      advancedMounts:
        gluetun:
          gluetun:
            - path: /gluetun
              subPath: config/gluetun
              readOnly: false











