immich:
  server:
    ingress:
      main:
        enabled: true
        annotations:
#            kubernetes.io/ingress.class: traefik
            #  traefik.ingress.kubernetes.io/router.middlewares: unlimited-body@kubernetescrd # we need to find a means to increase the body size for uploads for now this is not working
        hosts:
          - host: photos.oluwatobia.de
            paths:
              - path: /
                pathType: Prefix
  redis:
    enabled: true
    master:
      persistence:
        size: 5Gi
        storageClass: longhorn-storage-class
  env:
    DB_VECTOR_EXTENSION: pgvecto.rs
    DB_URL:
      valueFrom:
        secretKeyRef:
          name: database
          key: databaseUrl
  immich:
    persistence:
      library:
        existingClaim: immich-persistent-volume-claim
  postgresql:
    global:
      postgresql:
        auth:
          existingSecret: database


database:
  fullnameOverride: database
  version:
    postgresql: "15"
  imageCatalog:
    create: true
    images:
      - major: 15
        image: ghcr.io/tensorchord/cloudnative-pgvecto.rs:15.9-v0.3.0
  cluster:
    instances: 1
    services:
      disabledDefaultServices: [ "ro", "r" ]
    storage:
      size: 10Gi
      storageClass: longhorn-storage-class
    imageCatalogRef:
      kind: ImageCatalog
      name: database
      major: 15
    postgresql:
      shared_preload_libraries:
        - "vectors.so" #We need the pg vector extension for vector search and we are using this Reference https://github.com/tensorchord/cloudnative-pgvecto.rs/tree/main
    initdb:
      database: immich
      owner: homelabs
      secret:
        name: database
      postInitApplicationSQL: #Queries are to be run on the DB and not on the cluster
        - CREATE EXTENSION IF NOT EXISTS vectors;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - ALTER SCHEMA vectors OWNER TO homelabs;
#        - GRANT SELECT ON TABLE pg_vector_index_stat TO homelabs
