immich:
  redis:
    enabled: true
    master:
      persistence:
        size: 5Gi
        storageClass: longhorn-storage-class
  env:
    DB_DATABASE_NAME: immich
    DB_HOSTNAME:
        valueFrom:
            secretKeyRef:
              name: database
              key: hostname
    DB_USERNAME:
        valueFrom:
            secretKeyRef:
              name: database
              key: username
    DB_PASSWORD:
        valueFrom:
            secretKeyRef:
              name: database
              key: password
  immich:
    persistence:
      library:
        existingClaim: immich-persistent-volume-claim
  postgresql:
    global:
      postgresql:
        auth:
          existingSecret: database


database:
    fullnameOverride: database
    cluster:
        instances: 1
        services:
          disabledDefaultServices: ["ro", "r"]
        storage:
          size: 10Gi
          storageClass: longhorn-storage-class
        imageCatalogRef:
          kind: ImageCatalog
          name: cloud-native-vector-image
        enableSuperuserAccess: false
        postgresql:
          shared_preload_libraries:
            - "vectors.so" #We need the pg vector extension for vector search and we are using this Reference https://github.com/tensorchord/cloudnative-pgvecto.rs/tree/main
        initdb:
          database: immich
          owner: admin
          secret:
              name: database
          postInitSQL:
            - CREATE EXTENSION cube
            - CREATE EXTENSION earthdistance
            - CREATE EXTENSION vectors

