apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-user-login
  namespace: homelab-object-storage
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data: # Unfortunately ArgoCD required that template is escaped, Ref: https://github.com/external-secrets/external-secrets/issues/972#issuecomment-2034681905
        config.env: |
          export MINIO_ROOT_USER={{ "{{" }}.rootUser{{ "}}" }}
          export MINIO_ROOT_PASSWORD={{ "{{" }}.rootPassword{{ "}}" }}
          export MINIO_SERVER_URL=http://minio.homelab-object-storage.svc.cluster.local
          export MINIO_BROWSER_REDIRECT_URL=http://localhost:55049
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: rootUser
      remoteRef:
        key: "MinioObject/rootUser"
    - secretKey: rootPassword
      remoteRef:
        key: "MinioObject/rootPassword"
