grafana-prometheus:
  fullnameOverride: grafana-prometheus
  alertmanager:
    enabled: false

  prometheus:
    prometheusSpec:
      scrapeInterval: 15s
      retention: 4d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: prometheus-storage-class
            resources:
              requests:
                storage: 10Gi

  grafana:
    deploymentStrategy:
        type: Recreate
    serviceMonitor:
      interval: 5s
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    resources:
        requests:
            cpu: 50m
            memory: 225Mi
        limits:
            cpu: 1000m
            memory: 512Mi
    persistence:
        enabled: true
        storageClassName: grafana-storage-class
        accessModes:
            - ReadWriteOnce
        size: 10Gi
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          allowUiUpdates: false
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

    dashboards:
        default:
          cluster-metrics-overview:
            gnetId: 15661
            datasource: Prometheus
          cluster-overview:
            gnetId: 15757
            datasource: Prometheus
          pod-metrics:
            gnetId: 15760
            datasource: Prometheus
    datasources:
        datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
            type: prometheus
            access: proxy
            url: http://grafana-prometheus-prometheus.monitoring-system:9090
            isDefault: tru

  defaultRules:
    rules:
      windows: false
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false






