apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkwarden-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #Pods that will be using this are on the same node.
  persistentVolumeReclaimPolicy: Retain # Retain the volume after the claim is deleted
  storageClassName: linkwarden-storage-class
  local:
    path: /mnt/drive/core
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dlabs-worker-1  #This will be ported to Longhorn in the future.
