emulator:
  controllers:
    main:
      replicas: 1
      strategy: Recreate
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: dockurr/windows
            tag: latest
            pullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          env:
            - name: VERSION
              value: "win11"
            - name: RAM_SIZE
              value: "1G"
            - name: CPU_CORES
              value: "2"
            - name: DISK_SIZE
              value: "31G"
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 1Gi

  persistence:
    kvm-device:
      enabled: true
      type: hostPath
      hostPath: /dev/kvm
      advancedMounts:
        main:
          main:
            - path: /dev/kvm
    storage:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: windows-emulator-pvc
      advancedMounts:
        main:
          main:
            - path: /storage

  service:
    main:
      controller: main
      ports:
        http:
          port: 8006
          targetPort: 8006
        rdp:
          port: 3389
          targetPort: 3389

  ingress:
    main:
      enabled: true
      hosts:
        - host: windows.oluwatobia.de
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http

