homelab-tenant:
  secrets: ~
  tenant:
#    configuration:
#      name: root-user-login
    name: homelab
    pools:
      - servers: 1
        name: "minio-pool-1"
        volumesPerServer: 4
        storageClassName: longhorn-storage-class
        size: 5Gi
#    users:
#      - name: admin-user-console
#    configSecret:
#      name: root-user-login
#      accessKey: ~
#      secretKey: ~
#      existingSecret: true
