argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  server:
    extraArgs:
      - --insecure
    service:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: argo-cd.dyekan.com
