apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database
  namespace: immich-apps
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "Immich/databaseUsername"
    - secretKey: password
      remoteRef:
        key: "Immich/databasePassword"
    - secretKey: hostname
      remoteRef:
        key: "Immich/databaseHost"
