apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database
  namespace: immich-apps
spec:
  refreshPolicy: OnChange
  target:
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        databaseUrl: postgresql://{{ "{{" }}.username{{ "}}" }}:{{ "{{" }}.password{{ "}}" }}@database-rw.immich-apps.svc.cluster.local:5432/immich
        username: '{{ "{{" }}.username{{ "}}" }}'
        password: '{{ "{{" }}.password{{ "}}" }}'
  secretStoreRef:
    name: 1password-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "Immich/databaseUsername"
    - secretKey: password
      remoteRef:
        key: "Immich/databasePassword"
