bookmark:
  controllers:
    main:
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
          fsGroup: 0 # Set to 0 to allow root user access
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: ghcr.io/linkwarden/linkwarden
            tag: v2.10.0
            pullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: linkwarden
                  key: uri
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden
                  key: encryptionKey
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 3000
  ingress:
    main:
      hosts:
        - host: bookmark.oluwatobia.de
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: linkwarden-storage-class
      advancedMounts:
        main:
          main:
            - path: /data/data
              readOnly: false
            - path: /data/archives
              readOnly: false

database:
  fullnameOverride: linkwarden-db
  cluster:
    instances: 1
    storage:
      size: 10Gi
      storageClass: linkwarden-db-storage-class
    imageCatalogRef:
      major: 17
    initdb:
      database: linkwarden
      owner: linkwarden-admin
      secret:
        name: linkwarden
