bookmark:
  fullnameOverride: linkwarden
  postgresql:
    enabled: false
  linkwarden:
    domain: bookmark.dyekan.com
    database:
      existingSecret: linkwarden
    nextAuthSecret:
      value: encryptionKeyMec
      existingSecret:
        name: linkwarden
        key: encryptionKey
    data:
      filesystem:
        pvc:
          storageClass: linkwarden-storage-class
          size: 10Gi
#      s3:
#        bucketName: linkwarden   Consider using MinIO for S3 storage
#        region: us-east-1

database:
  fullnameOverride: linkwarden-db
  cluster:
    instances: 1
    resources:
     limits:
       cpu: 0.6
       memory: "100Mi"
     requests:
       cpu: 0.5
       memory: "120Mi"
    storage:
      size: 10Gi
      storageClass: linkwarden-db-storage-class
    imageCatalogRef:
      major: 17
    initdb:
      database: linkwarden
      owner: linkwarden-admin
      secret:
        name: linkwarden
