bookmark:
  fullnameOverride: linkwarden
  postgresql:
    enabled: false
  linkwarden:
    domain: bookmark.dyekan.com
    nextAuthSecret:
      existingSecret:
        name: linkwarden
        key: encryptionKey
    data:
      filesystem:
        pvc:
          size: 10Gi
#      s3:
#        bucketName: linkwarden   Consider using MinIO for S3 storage
#        region: us-east-1
    database:
      existingSecret: linkwarden

database:
  fullnameOverride: linkwardendb
  cluster:
    instances: 1
    storage:
      size: 2Gi
    imageCatalogRef:
      major: 17
    initdb:
      database: linkwarden
      owner: linkwarden-admin
      secret:
        name: linkwarden
