apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd-system
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
            namespace: argocd-system
          - name: cert-manager
            namespace: apps-system
          - name: cloud-native-operator
            namespace: apps-system
          - name: external-secret
            namespace: apps-system
          - name: grafana-prometheus
            namespace: observability-system
          - name: media-server
            namespace: media-server-apps
          - name: metallb
            namespace: apps-system
          - name: minio-operator
            namespace: minio-apps
          - name: minio-tenant
            namespace: homelab-object-storage
          - name: metrics-server
            namespace: observability-system
          - name: linkwarden
            namespace: linkwarden-apps
          - name: longhorn
            namespace: longhorn-system
          - name: traefik
            namespace: traefik-system

  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      source:
        path: "apps/{{.name}}"
        repoURL: https://github.com/uncle-tee/home-lab
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true # This is used because of Cloud Native Operator as it was throwing errors in the deployment in ArgoCd when deploying the CRDs https://github.com/cloudnative-pg/charts/issues/325
