apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd-system
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
            namespace: argocd-system
          - name: cert-manager
            namespace: apps-system
          - name: cloud-native-operator
            namespace: apps-system
          - name: metallb
            namespace: apps-system
          - name: traefik
            namespace: apps-system

  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      source:
        path: "apps/{{.name}}"
        repoURL: https://github.com/uncle-tee/home-lab
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
