apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  source:
    path: gitops/
    repoURL: https://github.com/uncle-tee/home-lab
    helm:
      valueFiles:
        - values.yaml
    targetRevision: HEAD
  project: default
  directory:
    recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
