apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-emulator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-storage-class

