{{- $global := .}}
{{- if .Values.metallb.ipPool }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ template "metallb.fullname" . }}-l2-advertisement
  namespace: {{ .Values.metallb.namespace }}
{{- end}}
