kube-prometheus:
  fullnameOverride: kube-prometheus
  kube-state-metrics:
    extraArgs:
      - --kubelet-insecure-tls
  prometheus:
    prometheusSpec:
      scrapeInterval: 15s
      retention: 4d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: prometheus-storage-class
            resources:
              requests:
                storage: 10Gi
  grafana:
    deploymentStrategy:
        type: Recreate
    serviceMonitor:
      interval: 5s
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    resources:
        requests:
            cpu: 50m
            memory: 225Mi
        limits:
            cpu: 1000m
            memory: 512Mi
    persistence:
        storageClassName: grafana-storage-class
        enabled: true
        accessModes:
            - ReadWriteOnce
        size: 10Gi
    extraVolumes:



